### ISSUE TITLE
Apresentação sobre Padrões Emergentes

### ISSUE THREAD

**Issue by DouglasMonteles** [UnBArqDsw2022-1/2022.1_G3_Bazar#66]
## Descrição da Issue
Apresentações, providas pelas equipes, sobre Padrões Emergentes

Tema escolhido: **Dependency Injection Pattern**

## Tasks:
- [x] Introdução (+/-2min)
- [x] Problema (+/- 2min
- [x] Solução (+/- 2min)
- [x] Exemplo (+/-3min)
- [x] Referências (+/- 1min)

**Comment by laispa** [comment]
Apresentação: Problema

**Comment by ubrando** [comment]
Slide: iNTRODUÇÃO

**Comment by EduardoGurgel** [comment]
Slide: Exemplo e Referências

**Comment by GabrielCostaDeOliveira** [comment]
Apresentação: introdução

**Comment by biancasofia** [comment]
Slide: Solução

**Comment by iagoomr** [comment]
Slide: Problema

**Comment by art1505** [comment]
Slide: Exemplos

**Comment by DouglasMonteles** [comment]
Apresentação: Exemplos

**Comment by DouglasMonteles** [comment]
Fazer o slide:
- Introdução @ubrando 
- Problema @iagoomr 
- Solução @biancasofia @ailtonaires 
- Exemplo e Referências @art1505 @EduardoGurgel

**Comment by DouglasMonteles** [comment]
Realizar a apresentação:
- Introdução @GabrielCostaDeOliveira  
- Problema @laispa  
- Solução @k3vin-batista  
- Exemplo e Referências @DouglasMonteles
