### ISSUE TITLE
Padrão GoFs - Comportamentais

### ISSUE THREAD

**Issue by GabrielCostaDeOliveira** [UnBArqDsw2022-1/2022.1_G3_Bazar#71]
## Descrição da Issue
 pelo menos DOIS Comportamentais, com nível de modelagem & nível de código evidenciados.

## Tasks:
- [x] GoFs comportamentais1
- [x] GoFs comportamentais2

**Comment by biancasofia** [comment]
Primeiro padrão: strategy

**Comment by art1505** [comment]
Segundo padrão: Template Method
